import { AIResponseSchema } from '../types';

export class SQLGenerator {
    generateInsertSQL(tableName: string, mapping: AIResponseSchema['mapping'], data: any[]): string[] {
        if (!data || data.length === 0) return [];

        const targetColumns = mapping.map(m => m.targetField);
        const statements: string[] = [];

        for (const row of data) {
            const values = mapping.map(m => {
                const sourceValue = row[m.sourceField];
                return this.formatValueForSQL(sourceValue, m.transformLogic);
            });

            const sql = `INSERT INTO ${tableName} (${targetColumns.join(', ')}) VALUES (${values.join(', ')});`;
            statements.push(sql);
        }

        return statements;
    }

    private formatValueForSQL(value: any, transformLogic?: string): string {
        if (value === null || value === undefined || value === '') {
            return 'NULL';
        }

        let formattedValue = value;

        // Apply simplistic JS-based transform logic if generated by AI
        if (transformLogic) {
            try {
                // Warning: In a real app we'd use a sandboxed evaluator, not eval
                // For demo/prototype purposes, evaluating basic transformations
                // e.g. "value.toUpperCase()" or "Number(value) * 10"
                const fn = new Function('value', `return ${transformLogic};`);
                formattedValue = fn(value);
            } catch (error) {
                console.warn(`Transform logic failed: ${transformLogic}`, error);
            }
        }

        if (typeof formattedValue === 'string') {
            // Basic SQL injection prevention / escaping for prototype
            const escaped = formattedValue.replace(/'/g, "''");
            return `'${escaped}'`;
        }

        return String(formattedValue);
    }
}
